[[event_listener]]
id = "custom-user-operation-notification-listener"
type = "org.wso2.carbon.user.core.listener.UserOperationEventListener"
name = "org.wso2.custom.user.operation.notification.listener.CustomUserOperationNotificationListener"
order = 1
enable = true